# Generated by Django 4.1.5 on 2023-03-04 05:35

import Destination.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_city', models.BooleanField(default=False)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('related_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=Destination.models.DestinationImage.nameFile)),
                ('image_url', models.URLField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Destination.destination')),
            ],
            options={
                'ordering': ['destination', 'id', 'image'],
            },
        ),
        migrations.AddConstraint(
            model_name='destinationimage',
            constraint=models.CheckConstraint(check=models.Q(('image__isnull', False), ('image_url__isnull', False), _connector='OR'), name='at_least_one_not_null'),
        ),
    ]
