# Generated by Django 4.1.5 on 2023-02-24 12:10

import Destination.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0003_remove_destination_location_destination_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Destination.models.DestinationImage.nameFile)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Destination.destination')),
            ],
        ),
    ]
