# Generated by Django 4.1.5 on 2023-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0004_destination_favorite_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
