# Generated by Django 4.1.5 on 2023-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0004_destinationimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['destination', 'id', 'image']},
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(upload_to='Destination/'),
        ),
    ]
