# Generated by Django 4.1.5 on 2023-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatri',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
