# Generated by Django 4.1.5 on 2023-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='type',
            field=models.CharField(blank=True, choices=[('DES', 'Destination'), ('FOD', 'Food'), ('ACT', 'Activity')], default=None, max_length=20, null=True),
        ),
    ]
