# Generated by Django 4.1.5 on 2023-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='type',
            field=models.CharField(choices=[('DES', 'Destination'), ('FOD', 'Food'), ('ACT', 'Activity')], max_length=20),
        ),
    ]
