# Generated by Django 4.1.5 on 2023-02-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_yatri_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatri',
            name='phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
