# Generated by Django 4.1.5 on 2023-03-01 13:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, upload_to='Countries/'),
        ),
    ]
