# Generated by Django 4.1.5 on 2023-02-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_yatri_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayatriexpert',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('PHr', 'per hour'), ('PSes', 'per session'), ('PProj', 'per visit'), ('PPrsn', 'per person')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sahayatriexpert',
            name='phone_no',
            field=models.CharField(default='XXXXXXXXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='sahayatriguide',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('PHr', 'per hour'), ('PDay', 'per hour'), ('PVst', 'per visit'), ('PPrsn', 'per person')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sahayatriguide',
            name='phone_no',
            field=models.CharField(default='XXXXXXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='sahayatriexpert',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sahayatriguide',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
