# Generated by Django 4.1.5 on 2023-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sahayatriexpert_cost_basis_sahayatriexpert_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='related_keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sahayatriguide',
            name='phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
