# Generated by Django 4.1.5 on 2023-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_language_flag_language_flag_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayatriexpert',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sahayatriguide',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sahayatriexpert',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('PHr', 'per hour'), ('PSes', 'per session'), ('PProj', 'per project'), ('PPrsn', 'per person')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sahayatriguide',
            name='cost_basis',
            field=models.CharField(blank=True, choices=[('PHr', 'per hour'), ('PDay', 'per day'), ('PVst', 'per visit'), ('PPrsn', 'per person')], default=None, max_length=10, null=True),
        ),
    ]
