# Generated by Django 4.1.5 on 2023-02-24 04:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sahayatriexpert_latitude_sahayatriexpert_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatri',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.Yatri.nameFile),
        ),
    ]
