# Generated by Django 4.1.5 on 2023-02-24 05:11

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_yatri_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahayatriexpert',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.SahayatriExpert.nameFile),
        ),
        migrations.AddField(
            model_name='sahayatriguide',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.SahayatriGuide.nameFile),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Y', 'Yatri'), ('G', 'Guide'), ('E', 'Expert')], default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='yatri',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='yatri',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.interest'),
        ),
        migrations.AlterField(
            model_name='yatri',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='yatri',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='yatri',
            name='phone_no',
            field=models.CharField(blank=True, default='XXXXXXXXXX', max_length=20),
        ),
    ]
