# Generated by Django 4.1.5 on 2023-03-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_policestation_alter_sahayatriexpert_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatri',
            name='languages',
            field=models.ManyToManyField(related_name='languages_yatri', to='accounts.language'),
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SOL', 'Solved'), ('WAT', 'Wating'), ('INI', 'Initiated')], default='WAT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sosrequest', to='accounts.policestation')),
                ('yatri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sosrequest', to='accounts.yatri')),
            ],
        ),
    ]
