# Generated by Django 4.1.5 on 2023-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sahayatriexpert_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahayatriexpert',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
