# Generated by Django 4.1.5 on 2023-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_sahayatriexpert_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahayatriexpert',
            name='experties',
        ),
        migrations.AddField(
            model_name='sahayatriexpert',
            name='expertise',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
