# Generated by Django 4.1.5 on 2023-03-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_yatri_languages_sosrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='yatri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sosrequestyatri', to='accounts.yatri'),
        ),
    ]
