# Generated by Django 4.1.5 on 2023-03-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0003_alter_destination_description'),
        ('Activites', '0006_alter_activity_description'),
        ('Food', '0004_food_favorites'),
        ('accounts', '0010_alter_sosrequest_yatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatri',
            name='favorites_activities',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorited_by', to='Activites.activity'),
        ),
        migrations.AddField(
            model_name='yatri',
            name='favorites_destinations',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorited_by', to='Destination.destination'),
        ),
        migrations.AddField(
            model_name='yatri',
            name='favorites_foods',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorited_by', to='Food.food'),
        ),
    ]
