# Generated by Django 4.1.5 on 2023-02-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_sahayatriexpert_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sahayatriexpert',
            old_name='Updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='sahayatriguide',
            old_name='Updated_at',
            new_name='updated_at',
        ),
    ]
