# Generated by Django 4.1.5 on 2023-03-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_yatri_favorites_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yatri',
            name='favorites_activities',
        ),
        migrations.RemoveField(
            model_name='yatri',
            name='favorites_destinations',
        ),
        migrations.RemoveField(
            model_name='yatri',
            name='favorites_foods',
        ),
    ]
