# Generated by Django 4.1.5 on 2023-02-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Y', 'Yatri'), ('G', 'Guide'), ('E', 'Expert')], default='Y', max_length=10),
        ),
    ]
