# Generated by Django 4.1.5 on 2023-03-04 10:46

import Food.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Destination', '0002_rename_is_city_destination_is_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('LOC', 'Local'), ('RST', 'Restaurant'), ('CAF', 'Cafe'), ('BAK', 'Bakery'), ('FTK', 'Food truck'), ('OTH', 'Others'), ('CONT', 'Continental'), ('FRN', 'French'), ('ITL', 'Italian'), ('IND', 'Indian'), ('EUR', 'European'), ('BAR', 'Bar'), ('ASN', 'Asian')], default='OTH', max_length=50)),
                ('phone_no', models.CharField(default='XXXXXXXXXX', max_length=20)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('related_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='Destination.destination')),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Food.models.FoodImage.nameFile)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Food.food')),
            ],
            options={
                'ordering': ['food', 'id', 'image'],
            },
        ),
    ]
