# Generated by Django 4.1.5 on 2023-02-25 09:10

import Food.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Food.models.FoodImage.nameFile)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Food.food')),
            ],
            options={
                'ordering': ['food', 'id', 'image'],
            },
        ),
    ]
