# Generated by Django 4.1.5 on 2023-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
