# Generated by Django 4.1.5 on 2023-03-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0008_alter_food_favorite_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
