# Generated by Django 4.1.5 on 2023-02-25 09:10

import Activites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Activites.models.ActivityImage.nameFile)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Activites.activity')),
            ],
            options={
                'ordering': ['activity', 'id', 'image'],
            },
        ),
    ]
