# Generated by Django 4.1.5 on 2023-03-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0002_rename_is_city_destination_is_area'),
        ('Activites', '0002_alter_activity_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='Destination.destination'),
        ),
    ]
