# Generated by Django 4.1.5 on 2023-02-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0002_activityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('ENT', 'Entertainment'), ('SPT', 'Sports'), ('ADV', 'Adventure'), ('LOC', 'Local'), ('OTH', 'Others')], default='OTH', max_length=10),
        ),
    ]
