# Generated by Django 4.1.5 on 2023-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0004_alter_activity_destination_alter_activity_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
