# Generated by Django 4.1.5 on 2023-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_yatri_favorites_activities_and_more'),
        ('Activites', '0006_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_activity', to='accounts.yatri'),
        ),
    ]
