# Generated by Django 4.1.5 on 2023-02-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_sahayatriexpert_latitude_sahayatriexpert_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=200)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('related_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest', models.ManyToManyField(to='accounts.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=200)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('related_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest', models.ManyToManyField(to='accounts.interest')),
            ],
        ),
    ]
